services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - postgres-server_default
      - redis-docker_default

networks:
  postgres-server_default:
    external: true
  redis-docker_default:
    external: true
